server:
  port: 8888

datasource:
  ip: 192.168.0.196
  port: 6543
  username: dbdonline
  password: kSJcek22D1IdB/eg7lfXCMgL4KrP6MjeTtVnhBXPF2KbzZDG7rC+8sCWKvQeNufULKpBw9zJ5YFssH1HW6GkSg==


druid:
  public:
    key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKjt6UO+y92PWupJsZ58OpBm3uSdj8FOsQwRyLEoWVv6eKpx6Ul/VduMcuvd8XRYq6z4qpoT/elHMgq0XzvcI0sCAwEAAQ==
spring:
  datasource:
    druid:
      filter:
        stat:
          slow-sql-millis: 100
